// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type EntityFileRelation struct {
	ID              int64   `json:"id"`
	EntityName      string  `json:"entity_name"`
	FileID          string  `json:"file_id"`
	RelationType    string  `json:"relation_type"`
	Confidence      float64 `json:"confidence"`
	SimilarityScore float64 `json:"similarity_score"`
	Metadata        string  `json:"metadata"`
	CreatedAt       int64   `json:"created_at"`
}

type GraphEdge struct {
	ID             string       `json:"id"`
	SrcID          string       `json:"src_id"`
	DstID          string       `json:"dst_id"`
	Rel            string       `json:"rel"`
	AttrsJson      string       `json:"attrs_json"`
	ValidFrom      time.Time    `json:"valid_from"`
	ValidTo        sql.NullTime `json:"valid_to"`
	IngestedAt     time.Time    `json:"ingested_at"`
	InvalidatedAt  sql.NullTime `json:"invalidated_at"`
	ProvenanceJson string       `json:"provenance_json"`
}

type GraphEdgesCurrent struct {
	ID             string       `json:"id"`
	SrcID          string       `json:"src_id"`
	DstID          string       `json:"dst_id"`
	Rel            string       `json:"rel"`
	AttrsJson      string       `json:"attrs_json"`
	ValidFrom      time.Time    `json:"valid_from"`
	ValidTo        sql.NullTime `json:"valid_to"`
	IngestedAt     time.Time    `json:"ingested_at"`
	InvalidatedAt  sql.NullTime `json:"invalidated_at"`
	ProvenanceJson string       `json:"provenance_json"`
}

type GraphEntity struct {
	ID        string       `json:"id"`
	Kind      string       `json:"kind"`
	Name      string       `json:"name"`
	Summary   string       `json:"summary"`
	AttrsJson string       `json:"attrs_json"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type OperationHistory struct {
	ID            string `json:"id"`
	WorkspaceID   string `json:"workspace_id"`
	OperationType string `json:"operation_type"`
	EntityPath    string `json:"entity_path"`
	OldPath       string `json:"old_path"`
	NewPath       string `json:"new_path"`
	Metadata      string `json:"metadata"`
	PerformedBy   string `json:"performed_by"`
	PerformedAt   int64  `json:"performed_at"`
}

type Workspace struct {
	ID        string `json:"id"`
	RootPath  string `json:"root_path"`
	Config    string `json:"config"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
